# .github/workflows/deploy.yml

name: Deploy backend on hetzner VM 

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/deploy.yml'

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up ssh key  
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.HETZNER_VM_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HETZNER_VM_HOST }}
          username: ${{ secrets.HETZNER_VM_USERNAME }}
          key: ${{ secrets.HETZNER_VM_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/deployer/geography_board_game/backend
            git pull origin main
            docker-compose down
            docker-compose up -d --build
            docker image prune -f